Merging

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+function install_man() {
+	cp docs/mirage.1.gz /usr/share/man/man1/mirage.1.gz
+	if [ $? -ne 0 ]
+	then
+		echo "WARNING: Could not install Mirage's man page. Please run the command \"./configure --man\" with super user privledges to install the man page." > &2
+	else
+		echo "Man page installed"
+	fi
+}
+
+if [ $1 = "--man" ]
+then
+	install_man()
+	exit
+fi
+
 #First, I need to find what python interperiter to use.
 
 interpereters=($(whereis -b python | sed 's/ /\n/g' | grep "python3$\|python3.[[:digit:]]$"))
@@ -34,6 +50,7 @@ then
 	$interpereter -m venv "mirage_venv"
 	if [ $? -ne 0 ]
 	then
+		echo "Error: Could not construct virtual environment. Please make sure your chosen python interpreter has the venv module installed, or try another interpreter" >&2
 		exit
 	fi
 	source mirage_venv/bin/activate
@@ -100,6 +117,7 @@ then
 	echo "alias mirage=\"$LA_HOME/scripts/mirage\"" >> "$HOME/.bashrc"
 	echo "Alias made. Mirage can now be run from any directory with the command \"mirage\"."
 fi
+install_man()
 echo "mirage configured. For info on using mirage, see the man entry."
 echo "To finish compiling all components, run make"
 
