Pushing up perhaps the final result?

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,13 +1,39 @@
 #!/bin/bash
+ORANGE='\033[0;33m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 
+function install_man() {
+	cp docs/mirage.1.gz /usr/share/man/man1/mirage.1.gz
+	if [ $? -ne 0 ]
+	then
+		echo -e "${ORANGE}WARNING: Could not install Mirage's man page. Please run the command \"./configure --man\" with super user priviledges to install the man page.${NC}" > /dev/stderr
+	else
+		echo -e "${GREEN}Man page installed${NC}"
+	fi
+}
+
+
+
+
+
+# Here starts the actual script.
+#First, if the --man flag, run that and exit.
+if [ $1 = "--man" ]
+then
+	install_man
+	exit
+fi
+
+#Now for the regular config setup.
 #First, I need to find what python interperiter to use.
 
-interpereters=($(whereis -b python | sed 's/ /\n/g' | grep "python3$\|python3.[[:digit:]]$"))
+interpereters=($(whereis -b python | sed 's/ /\n/g' | grep "python3$\|python3.[[:digit:]]$" | xargs file -L | grep "interpreter" | sed "s/://g" | awk '{print $1 }'))
 build_modes=('.analysis_pip' '.sim_pip' '.dev_pip')
 
 if [ interpereters = "" ]
 then
-	echo "Error: Mirage requires a python3 interpereter. Please install python3 and try again"
+	echo -e "${ORANGE}Error: Mirage requires a python3 interpereter. Please install python3 and try again${NC}"
 	exit
 fi
 
@@ -23,9 +49,12 @@ for ((idx=0; idx<${#interpereters[@]}; ++idx)); do
     echo "	[$idx]:" "${interpereters[idx]}"
 done
 read -p "> " int_ind
-
+if [ $int_ind -ge ${#interpereters[@]} ]
+then
+	echo -e "${ORANGE} ERROR: Please select a valid interpereter from the list"
+	exit
+fi
 interpereter="${interpereters[int_ind]}"
-echo "Selected $interpereter"
 echo ""
 echo "Should I create a virtual environment for Mirage?"
 read -p "y/n (Recommended yes): " mk_venv
@@ -34,6 +63,7 @@ then
 	$interpereter -m venv "mirage_venv"
 	if [ $? -ne 0 ]
 	then
+		echo -e "${ORANGE}Error: Could not construct virtual environment. Please make sure your chosen python interpreter has the venv module installed, or try another interpreter${NC}" > /dev/stderr
 		exit
 	fi
 	source mirage_venv/bin/activate
@@ -47,19 +77,22 @@ echo "	[0]: Dependencies for analyzing simulation results"
 echo "	[1]: Dependencies for performing simulations"
 echo "	[2]: Dependencies for developers"
 read -p "> " dependency_col
+if [ $dependency_col -ge 3 ]
+then
+	echo -e "${ORANGE} ERROR: Please select a valid dependency pack from the list"
+	exit
+fi
 build_pack="${build_modes[dependency_col]}"
 pip install --disable-pip-version-check wheel
 pip install --disable-pip-version-check -r "$build_pack"
 if [ $? -ne 0 ]
 then
-	echo "Error. Could not install requested packages using pip."
+	echo -e "${ORANGE}Error. Could not install requested packages using pip.${NC}"
 	exit
 else
 	echo "Python environment configured."
 fi
 
-echo "Setting up pyspark environment"
-pip --disable-pip-version-check install pyspark
 JAR_HOME=""
 if [ -d "spark_mirage" ] 
 then
@@ -98,9 +131,10 @@ read -p "y/n (recommend yes):" make_alias
 if [ -n "$(echo "$make_alias" | grep -i -o "y")" ]
 then
 	echo "alias mirage=\"$LA_HOME/scripts/mirage\"" >> "$HOME/.bashrc"
-	echo "Alias made. Mirage can now be run from any directory with the command \"mirage\"."
+	echo -e "${GREEN}Alias made. Mirage can now be run from any directory with the command \"mirage\".${NC}"
 fi
-echo "mirage configured. For info on using mirage, see the man entry."
+install_man
+echo -e "${GREEN}mirage configured. For info on using mirage, see the man entry.${NC}"
 echo "To finish compiling all components, run make"
 
 
